spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: koreait

#mybatis:
#  mapper-locations: mapper/**/*.xml
#  type-aliases-package: com.example.fbt.dao